"""add cooking methods

Revision ID: 70f910970b33
Revises: acb461aa7f84
Create Date: 2026-05-05 01:16:11.623324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70f910970b33'
down_revision: Union[str, None] = 'acb461aa7f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking_mediums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cooking_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('protein_factor', sa.Float(), nullable=False),
    sa.Column('fat_factor', sa.Float(), nullable=False),
    sa.Column('carb_factor', sa.Float(), nullable=False),
    sa.Column('weight_change_pct', sa.Float(), nullable=False),
    sa.Column('absorbs_medium', sa.Boolean(), nullable=False),
    sa.Column('medium_absorption_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('dishes', sa.Column('cooking_method_id', sa.Integer(), nullable=True))
    op.add_column('dishes', sa.Column('cooking_medium_id', sa.Integer(), nullable=True))
    op.add_column('dishes', sa.Column('medium_amount_g', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'cooking_mediums', ['cooking_medium_id'], ['id'])
    op.create_foreign_key(None, 'dishes', 'cooking_methods', ['cooking_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'medium_amount_g')
    op.drop_column('dishes', 'cooking_medium_id')
    op.drop_column('dishes', 'cooking_method_id')
    op.drop_table('cooking_methods')
    op.drop_table('cooking_mediums')
    # ### end Alembic commands ###